version: '3.4'

services:
  mssql:
    container_name: 'mssql-wapizza'
    ports:
      - "1433:1433"
    volumes:
      - db-data:/var/opt/mssql/data
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "#sql-pass22_"
    user: root
    restart: unless-stopped


  seq:
    container_name: 'seq-wapizza'
    ports:
      - "5122:80"
    environment:
      ACCEPT_EULA: "Y"

  wa.pizza.web:
    container_name: 'web-wapizza'
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5123:80"

volumes:
  db-data: