name: .NET

on:
  push:
    branches: [ "feature/12-add-code-coverage" ]
  pull_request:
    branches: [ "feature/12-add-code-coverage" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: C:\Users\Asus\source\repos\CleanArchitecture

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --collect:"XPlat Code Coverage"
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
