name: .NET

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore CleanArchitecture.sln
    - name: Build the stack
      run: docker-compose up -d
    - name: Test
      run: docker run --network container:web-wapizza wa.pizza.web -s --retry 10 --retry-connrefused http://localhost:5123/
    - name: Codecov
      uses: codecov/codecov-action@v1.5.2
